import { CardModel } from './types'

const mtrx = {
  '2': {
    '2': true,
    '3': true,
    '4': true,
    '5': true,
    '6': true,
    '7': true,
    '8': true,
    '9': true,
    '10': true,
    J: true,
    Q: true,
    K: true,
    A: true,
  },
  '3': {
    '2': true,
    '3': true,
    '4': false,
    '5': false,
    '6': false,
    '7': true,
    '8': false,
    '9': false,
    '10': false,
    J: false,
    Q: false,
    K: false,
    A: false,
  },
  '4': {
    '2': true,
    '3': true,
    '4': true,
    '5': false,
    '6': false,
    '7': true,
    '8': false,
    '9': false,
    '10': false,
    J: false,
    Q: false,
    K: false,
    A: false,
  },
  '5': {
    '2': true,
    '3': true,
    '4': true,
    '5': true,
    '6': true,
    '7': true,
    '8': true,
    '9': true,
    '10': true,
    J: true,
    Q: true,
    K: true,
    A: false,
  },
  '6': {
    '2': true,
    '3': true,
    '4': true,
    '5': true,
    '6': true,
    '7': true,
    '8': false,
    '9': false,
    '10': false,
    J: false,
    Q: false,
    K: false,
    A: false,
  },
  '7': {
    '2': true,
    '3': true,
    '4': true,
    '5': true,
    '6': true,
    '7': true,
    '8': true,
    '9': true,
    '10': true,
    J: true,
    Q: true,
    K: true,
    A: false,
  },
  '8': {
    '2': true,
    '3': true,
    '4': true,
    '5': true,
    '6': true,
    '7': true,
    '8': true,
    '9': true,
    '10': true,
    J: true,
    Q: true,
    K: true,
    A: true,
  },
  '9': {
    '2': true,
    '3': true,
    '4': true,
    '5': true,
    '6': true,
    '7': false,
    '8': true,
    '9': true,
    '10': false,
    J: false,
    Q: false,
    K: false,
    A: false,
  },
  '10': {
    '2': true,
    '3': true,
    '4': true,
    '5': true,
    '6': true,
    '7': false,
    '8': true,
    '9': true,
    '10': true,
    J: true,
    Q: true,
    K: true,
    A: false,
  },
  J: {
    '2': true,
    '3': true,
    '4': true,
    '5': true,
    '6': true,
    '7': false,
    '8': true,
    '9': true,
    '10': true,
    J: true,
    Q: false,
    K: false,
    A: false,
  },
  Q: {
    '2': true,
    '3': true,
    '4': true,
    '5': true,
    '6': true,
    '7': false,
    '8': true,
    '9': true,
    '10': true,
    J: true,
    Q: true,
    K: false,
    A: false,
  },
  K: {
    '2': true,
    '3': true,
    '4': true,
    '5': true,
    '6': true,
    '7': false,
    '8': true,
    '9': true,
    '10': true,
    J: true,
    Q: true,
    K: true,
    A: false,
  },
  A: {
    '2': true,
    '3': true,
    '4': true,
    '5': true,
    '6': true,
    '7': true,
    '8': true,
    '9': true,
    '10': true,
    J: true,
    Q: true,
    K: true,
    A: true,
  },
}

export const canCardPlay = (
  card: CardModel,
  destination: CardModel,
): boolean => {
  if (!destination) return true
  if (card.value === '8') return true
  if (destination.value === 'J') {
    return card.suit === destination.suit || card.value === 'J'
  }

  return mtrx[card.value][destination.value]
}
